name: inf-ae
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - h5py>=3.1.0
  - scipy>=1.8.0
  - numpy==1.26.4
  - numba
  - pandas
  - tqdm
  - scikit-learn
  - pip:
      - jax==0.4.23 # higher than this breaks `from jax import random`
      - neural_tangents>=0.5.0

# Important:
# jax depends on a compatible jaxlib; run the following after activating the env to get it:
# pip install jaxlib==0.4.23+cuda12.cudnn89 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
# Note: the jaxlib dependency depends on your machine (gpu/no gpu; cuda version)
