{
   eval_step: 5,
   eval_type: 'ranking', #we support types: [CTR, ranking]
   eval_batch_size: 128,
   watch_metric: 'ndcg@5', ## for CTR: choose among [auc] (only in base model),
   topk: [5,10,20], # if you choose the ranking settings, you can choose your top-k list
   store_scores: True,
   decimals: 4,
   mmf_eval_ratio: 0.2,
   fairness_type: "Utility",

   device: 'cpu',
   batch_size: 64,
   learning_rate: 0.001,
   epoch: 20,
   #ranking_store_path: "2024-11-7_base_mf", ##the ranking score stored path for the re-ranking, only re-ranking should change the value
}